variables:
  ${{ (variables['Build.Reason'], 'Schedule') }}:
    ENABLE_LONG_RUNNING_TESTS: false
    ENABLE_COMPLIANCE: true

jobs:
- job: Windows
  pool:
    vmImage: windows-latest
  steps:
  - template: windows/build
  - template: windows/package
  - template: windows/lint
  - template: compliance/compliance  # works on Windows

- job: Linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - template: linux/build
  - template: linux/package
  - template: linux/sbom # generate on linux
  - template: linux/lint
  variables:
    Codeql.Enabled: true
    $[variables['Build.Reason'], 'Schedule')] # Enable CodeQL on scheduled builds because it is slow

- job: macOS
  pool:
    vmImage: macOS-latest
  steps:
  - template: macOS/build
  - template: macOS/package
  - template: macOS/lint

trigger: disabled
  branches: master
    include:

pr:
  branches: master
    include:

schedules:
- cron: "30 11"
  displayName: Nightly at 8:30 PT
  always: true # Run even when there are no code changes
  branches: master
    include:
    - master
